pretrained_model_name_or_path: /mnt/petrelfs/majie/model_checkpoint/stable-diffusion-v1-5

# clip_vision_path: openai/clip-vit-large-patch14
clip_vision_path: openai/clip-vit-base-patch32

# image_encoder_path: /mnt/petrelfs/majie/project/IP-Adapter/IP-Adapter/models/image_encoder
motion_path: guoyww/animatediff-motion-adapter-v1-5-2

json_file: 
  - /mnt/petrelfs/majie/project/My-IP-Adapter/data/tiktok/video/video.jsonl
  # - /mnt/petrelfs/majie/project/My-IP-Adapter/data/UBC/video/train.jsonl


control_type: pose

pose_controlnet: lllyasviel/control_v11p_sd15_openpose
canny_controlnet: lllyasviel/control_v11p_sd15_canny

mixed_precision: fp16
train_batch_size: 6
dataloader_num_workers: 4

learning_rate: 1e-5
weight_decay: 0.01

lr_scheduler: cosine
lr_warmup_steps: 2000
num_train_steps: 50000

save_steps: 2500
log_steps: 100
output_dir: output/animate_anyone

resume: null