pretrained_model_name_or_path: /mnt/petrelfs/majie/model_checkpoint/stable-diffusion-v1-5
image_encoder_path: /mnt/petrelfs/majie/project/IP-Adapter/IP-Adapter/models/image_encoder

json_file: 
  - /mnt/petrelfs/majie/project/My-IP-Adapter/data/cctv/cctv_all.jsonl
  - /mnt/petrelfs/majie/project/My-IP-Adapter/data/cctv/aug/sixpose.jsonl

control_type: canny

pose_controlnet: lllyasviel/control_v11p_sd15_openpose
canny_controlnet: lllyasviel/control_v11p_sd15_canny

mixed_precision: fp16
train_batch_size: 16
dataloader_num_workers: 4

learning_rate: 1e-4
weight_decay: 0.01

lr_scheduler: cosine
lr_warmup_steps: 2000
num_train_steps: 50000

save_steps: 500
log_steps: 500
output_dir: output/cctv

resume: null