pretrained_model_name_or_path: /mnt/petrelfs/majie/model_checkpoint/stable-diffusion-v1-5
motion_path: guoyww/animatediff-motion-adapter-v1-5-2
reference_path: /mnt/petrelfs/majie/project/My-IP-Adapter/output/reference_net/2023-12-04-17-27/checkpoint-30000/pytorch_model.bin
json_file: 
  - /mnt/petrelfs/majie/project/My-IP-Adapter/data/tiktok/video/video.jsonl
num_frames: 24

control_type: pose

pose_controlnet: lllyasviel/control_v11p_sd15_openpose
canny_controlnet: lllyasviel/control_v11p_sd15_canny

mixed_precision: fp16
train_batch_size: 1
dataloader_num_workers: 4

learning_rate: 1e-4
weight_decay: 0.01

lr_scheduler: cosine
lr_warmup_steps: 2000
num_train_steps: 50000

save_steps: 500
log_steps: 100
output_dir: output/temporal

resume: null